In [16]:
import time
# Matrix A
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

# Matrix B
B = [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]]



# Function for matrix multiplication
def matrix_multiplication(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix2[0])):
            element = 0
            for k in range(len(matrix2)):
                element += matrix1[i][k] * matrix2[k][j]
            row.append(element)
        result.append(row)
    return result

# Test the matrix multiplication function

start_time = time.time()


C = matrix_multiplication(A, B)

end_time = time.time()
execution_time = end_time - start_time

print("Execution time:", execution_time, "seconds")
print(C)


Execution time: 3.266334533691406e-05 seconds
[[84, 90, 96], [201, 216, 231], [318, 342, 366]]


In [14]:
import numpy as np
import time

# Create matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Create matrix B
B = np.array([[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]])

# Perform matrix multiplication
start_time = time.time()

C = np.matmul(A, B)
end_time = time.time()
execution_time = end_time - start_time

print("Execution time:", execution_time, "seconds")
print(C)


Execution time: 6.318092346191406e-05 seconds
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [21]:
import numpy as np
# Create matrix
matrix = np.array([[3,5],[2,2]])

# Create vector
vector = np.array([2,2])

result = np.matmul(np.linalg.inv(matrix), vector.transpose())
print(result)


[ 1.5 -0.5]


In [25]:
import numpy as np

# Definice funkce pro Cramerovo pravidlo
def cramer_rule(matrix, vector):
    # Výpočet determinantu matice
    det_matrix = np.linalg.det(matrix)
    num_variables = len(vector)
    solutions = []
    
    for i in range(num_variables):
        modified_matrix = matrix.copy()
        # Nahrazení i-tého sloupce matice vektorem
        modified_matrix[:, i] = vector
        # Výpočet determinantu upravené matice
        det_modified_matrix = np.linalg.det(modified_matrix)
        # Výpočet řešení pomocí Cramerova pravidla
        solution = det_modified_matrix / det_matrix
        solutions.append(solution)
    
    return solutions

# Příklad použití
rank = np.linalg.matrix_rank(matrix)
if rank != len(vector):
    print("Soustava rovnic nemá řešení")
    exit()
vector = np.array([5,1,11])

# Volání funkce cramer_rule pro výpočet řešení
solutions = cramer_rule(matrix, vector)
print("Řešení:", solutions)


Řešení: [2.0000000000000013, -2.0000000000000004, 3.0000000000000013]
